version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: kavita_server_1 
      APP_PORT: 5000
      PROXY_AUTH_ADD: "false"
 
  server:
    image: kizaing/kavita:latest
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "5000:5000"
    volumes:
      - ${UMBREL_ROOT}/data/storage/kavita:/data
      - ${APP_DATA_DIR}/data/kavita/config:/kavita/config
        #environment:
        #  - PUID=1000
        #  - PGID=1000
