version: '3'
services:
   app_proxy:
    environment:
      APP_HOST: kavita_server_1 
      APP_PORT: 5000
      PROXY_AUTH_ADD: "false"
 
    kavita:
        image: kizaing/kavita:latest
        restart: on-failure
        hostname: "${DEVICE_HOSTNAME}"
        volumes:
            - ${UMBREL_ROOT}/data/storage/kavita:/data
            - ${APP_DATA_DIR}/config:/kavita/config
        ports:
            - "5000:5000"
        environment:
          - PUID=1000
          - PGID=1000
        
        #Uncomment if you want to implement healthchecks
        #healthcheck:
        #   test: curl --fail http://localhost:5000 || exit 1
        #   interval: 300s
        #   retries: 3
        #   start_period: 30s
        #   timeout: 15s
