version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: kavita_server_1 
      APP_PORT: 5048
      PROXY_AUTH_ADD: "false"
 
  server:
    image: kizaing/kavita:latest
    restart: on-failure
    hostname: "${DEVICE_HOSTNAME}"
    volumes:
      - ${UMBREL_ROOT}/data/storage/kavita:/data
      - ${APP_DATA_DIR}/data/config:/kavita/config
    ports:
      - 5000:5000
      - 5000:5000/udp
    environment:
      - PUID=1000
      - PGID=1000
